(function($){"use strict";if(!$.app.menu.is_touch_device()){if($('.chat-application .chat-user-list').length>0){var chat_user_list=new PerfectScrollbar(".chat-user-list");}
if($('.chat-application .profile-sidebar-area .scroll-area').length>0){var chat_user_list=new PerfectScrollbar(".profile-sidebar-area .scroll-area");}
if($('.chat-application .user-chats').length>0){var chat_user=new PerfectScrollbar(".user-chats",{wheelPropagation:false});}
if($('.chat-application .user-profile-sidebar-area').length>0){var user_profile=new PerfectScrollbar(".user-profile-sidebar-area");}}
else{$(".chat-user-list").css("overflow","scroll");$(".profile-sidebar-area .scroll-area").css("overflow","scroll");$(".user-chats").css("overflow","scroll");$(".user-profile-sidebar-area").css("overflow","scroll");}
$('.chat-application .sidebar-profile-toggle').on('click',function(){$('.chat-profile-sidebar').addClass('show');$('.chat-overlay').addClass('show');});$('.chat-application .user-profile-toggle').on('click',function(){$('.user-profile-sidebar').addClass('show');$('.chat-overlay').addClass('show');});$('.chat-application .user-status input:radio[name=userStatus]').on('change',function(){var $className="avatar-status-"+this.value;$(".header-profile-sidebar .avatar span").removeClass();$(".sidebar-profile-toggle .avatar span").removeClass();$(".header-profile-sidebar .avatar span").addClass($className+" avatar-status-lg");$(".sidebar-profile-toggle .avatar span").addClass($className);});$(".chat-application .close-icon").on('click',function(){$('.chat-profile-sidebar').removeClass('show');$('.user-profile-sidebar').removeClass('show');if(!$(".sidebar-content").hasClass("show")){$('.chat-overlay').removeClass('show');}});$(".chat-application .sidebar-close-icon").on('click',function(){$('.sidebar-content').removeClass('show');$('.chat-overlay').removeClass('show');});$(".chat-application .chat-overlay").on('click',function(){$('.app-content .sidebar-content').removeClass('show');$('.chat-application .chat-overlay').removeClass('show');$('.chat-profile-sidebar').removeClass('show');$('.user-profile-sidebar').removeClass('show');});$(".chat-application .chat-user-list ul li").on('click',function(){if($('.chat-user-list ul li').hasClass('active')){$('.chat-user-list ul li').removeClass('active');}
$(this).addClass("active");$(this).find(".badge").remove();if($('.chat-user-list ul li').hasClass('active')){$('.start-chat-area').addClass('d-none');$('.active-chat').removeClass('d-none');}
else{$('.start-chat-area').removeClass('d-none');$('.active-chat').addClass('d-none');}});var chatContainer=$(".user-chats");$(".chat-users-list-wrapper li").on("click",function(){chatContainer.animate({scrollTop:chatContainer[0].scrollHeight},400)});$(".chat-application .favorite i").on("click",function(e){$(this).parent('.favorite').toggleClass("warning");e.stopPropagation();});$('.chat-application .menu-toggle').on('click',function(e){$('.app-content .sidebar-left').removeClass('show');$('.chat-application .chat-overlay').removeClass('show');});if($(window).width()<992){$('.chat-application .sidebar-toggle').on('click',function(){$('.app-content .sidebar-content').addClass('show');$('.chat-application .chat-overlay').addClass('show');});}
if($(window).width()>992){if($('.chat-application .chat-overlay').hasClass('show')){$('.chat-application .chat-overlay').removeClass('show');}}
$(".user-chats").scrollTop($(".user-chats > .chats").height());$(".chat-application #chat-search").on("keyup",function(){var value=$(this).val().toLowerCase();if(value!=""){$(".chat-user-list .chat-users-list-wrapper li").filter(function(){$(this).toggle($(this).text().toLowerCase().indexOf(value)>-1);});}
else{$(".chat-user-list .chat-users-list-wrapper li").show();}});})(jQuery);$(window).on("resize",function(){if($(window).width()>992){if($('.chat-application .chat-overlay').hasClass('show')){$('.app-content .sidebar-left').removeClass('show');$('.chat-application .chat-overlay').removeClass('show');}}
if($(window).width()<992){if($('.chat-application .chat-profile-sidebar').hasClass('show')){$('.chat-profile-sidebar').removeClass('show');}
$('.chat-application .sidebar-toggle').on('click',function(){$('.app-content .sidebar-content').addClass('show');$('.chat-application .chat-overlay').addClass('show');});}});function enter_chat(source){var message=$(".message").val();if(message!=""){var html='<div class="chat-content">'+"<p>"+message+"</p>"+"</div>";$(".chat:last-child .chat-body").append(html);$(".message").val("");$(".user-chats").scrollTop($(".user-chats > .chats").height());}}